-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('NEW_MESSAGE', 'MENTION', 'SYSTEM', 'ROLE_CHANGED', 'POST_COMMENT', 'COMMENT_REPLY', 'POST_REACTION', 'NEW_FOLLOWER', 'GROUP_INVITE', 'MODERATION', 'GROUP_ACTIVITY', 'POST_SHARE', 'SECURITY') NOT NULL DEFAULT 'SYSTEM';

-- AlterTable
ALTER TABLE `post` ADD COLUMN `repostOfId` VARCHAR(191) NULL,
    ADD COLUMN `shareCount` INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX `post_repostOfId_idx` ON `post`(`repostOfId`);

-- AddForeignKey
ALTER TABLE `post` ADD CONSTRAINT `post_repostOfId_fkey` FOREIGN KEY (`repostOfId`) REFERENCES `post`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

